### ISSUE TITLE
Annotations fail on jobs with multiple targets

### ISSUE THREAD

**Issue by andrewbanchich** [actions-rs/clippy-check#138]
Workflow file:

```
on:
  pull_request:
    branches: [ master ]

name: Clippy
jobs:
  rustfmt:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
 
  clippy_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
  
      - uses: actions-rs/clippy-check@v1
        env:
          SQLX_OFFLINE: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
```

This will create annotations for the first completed Clippy check, but any others will never finish.

![Screenshot_20210417-092702~2](https://user-images.githubusercontent.com/13824577/115115012-2157a180-9f60-11eb-9db9-683c508ece6f.png)
![Screenshot_20210417-092713~2](https://user-images.githubusercontent.com/13824577/115115013-2157a180-9f60-11eb-9050-431c61da143f.png)
