### ISSUE TITLE
Option to only create annotations instead of using a separate check run

### ISSUE THREAD

**Issue by Purpzie** [actions-rs/clippy-check#156]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation
It would be nice if `actions-rs/clippy-check` worked like `actions-rs/cargo`, and *just* created annotations. This would prevent it from creating an unnecessary check run to display the results in a table. The cargo action doesn't display the full details like clippy-check does.

## Workflow example

```yaml
- uses: actions/rs@clippy-check@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    only-annotations: true
```

## Additional context
This would also be useful to prevent #45 from happening until that gets fixed one day.
