### ISSUE TITLE
Add option to fail check on warnings

### ISSUE THREAD

**Issue by sffc** [actions-rs/clippy-check#82]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

Currently, [the check fails only when clippy returns an error](https://github.com/actions-rs/clippy-check/blob/master/src/check.ts#L138).  This makes it hard to notice when warnings occur, since Clippy warnings can also be helpful.  As usual, noisy warnings can be disabled in code with `#[allow(...)]`.  I would therefore like the option for the check to fail on both warnings and errors.

I would like this behavior both on in-repo PRs and forked PRs.

## Workflow example

```yaml
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features
        failure-mode: warnings
```

## Additional context

See discussion in https://github.com/unicode-org/icu4x/pull/161.  Currently we are adding two different checks, the actions-rs version for the nice HTML in supported PRs, and a command line version with `-- -D warnings` to cause a failed check.  It would simply and speed up our workflow if we didn't need the second check only for the check failure.

CC @echeran @Manishearth
